### ISSUE TITLE
I'm having this issue

### ISSUE THREAD

**Issue by amhorny** [suyashl13/Lecture-Spam-Bot#1]
Password Entered
Bot login Sucessfull...
Permissions not required
Oops! Invalid Login Credentials
ERR in excepting alert
Waiting for host to let you in, if host does not allows you in within 10 seconds Program will be terminated
Wait time : 1
Wait time : 2
Wait time : 3
Wait time : 4
Wait time : 5
Wait time : 6
Wait time : 7
Wait time : 8
Wait time : 9
Wait time : 10
Host Denied

**Comment by suyashl13** [comment]
I have resolved it 😉
